// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using dotnet_example.Data;

#nullable disable

namespace dotnet_example.Migrations
{
    [DbContext(typeof(BaseDataContext))]
    partial class BaseDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("dotnet_example.Models.BOL", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AccessorialsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BOLCommoditiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BOLImagesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BOLPaymentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BOLReferenceNumbersId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BOLShipmentTotalsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BillToId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("CustomsBrokerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Function")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsTest")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OriginId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedPickupDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RequestorRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpecialInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessorialsId");

                    b.HasIndex("BOLCommoditiesId");

                    b.HasIndex("BOLImagesId");

                    b.HasIndex("BOLPaymentId");

                    b.HasIndex("BOLReferenceNumbersId");

                    b.HasIndex("BOLShipmentTotalsId");

                    b.HasIndex("BillToId");

                    b.HasIndex("CustomsBrokerId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("BOLs");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorials", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AppointmentDetailsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CodId")
                        .HasColumnType("uuid");

                    b.Property<List<string>>("Codes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("FullValueCoverageDetailsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("HazardousDetailsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LimitedAccessTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MarkDetailsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SortAndSegregateDetailsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TimeCriticalDetailsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentDetailsId");

                    b.HasIndex("CodId");

                    b.HasIndex("FullValueCoverageDetailsId");

                    b.HasIndex("HazardousDetailsId");

                    b.HasIndex("LimitedAccessTypeId");

                    b.HasIndex("MarkDetailsId");

                    b.HasIndex("SortAndSegregateDetailsId");

                    b.HasIndex("TimeCriticalDetailsId");

                    b.ToTable("BOLAccessorials");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsAppointmentDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeliveryEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeliveryStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PickUpEnd")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("PickupStart")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLAccessorialsAppointmentDetails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsCod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("CustomerCheckAcceptable")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RemitToId")
                        .HasColumnType("uuid");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("RemitToId");

                    b.ToTable("BOLAccessorialsCods");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsFullValueCoverageDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MonetaryValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLAccessorialsFullValueCoverageDetails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsHazardousDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLAccessorialsHazardousDetails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsHazardousDetailsEmergencyContact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BOLAccessorialsHazardousDetailsId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BOLAccessorialsHazardousDetailsId")
                        .IsUnique();

                    b.ToTable("BOLAccessorialsHazardousDetailsEmergencyContacts");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsLimitedAccessType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLAccessorialsLimitedAccessTypes");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsMarkDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Pieces")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLAccessorialsMarkDetails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsSortAndSegregateDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Pieces")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLAccessorialsSortAndSegregateDetails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsTimeCriticalDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("End")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLAccessorialsTimeCriticalDetails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLCommmoditiesLineItems", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BOLCommoditiesHandlingUnitsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BOLCommoditiesHazardousDetailsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Hazardous")
                        .HasColumnType("boolean");

                    b.Property<string>("HazardousDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nmfc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NmfcSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackagingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Pieces")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BOLCommoditiesHandlingUnitsId");

                    b.HasIndex("BOLCommoditiesHazardousDetailsId");

                    b.ToTable("BOLCommmoditiesLineItems");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLCommodities", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("LineItemLayout")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLCommodities");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLCommoditiesHandlingUnits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BOLCommoditiesId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DimensionsUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("Length")
                        .HasColumnType("integer");

                    b.Property<bool?>("Stackable")
                        .HasColumnType("boolean");

                    b.Property<int?>("TareWeight")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BOLCommoditiesId");

                    b.ToTable("BOLCommoditiesHandlingUnits");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLCommoditiesHazardousDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PackingGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Propername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TechnicalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnnaNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BOLCommoditiesHazardousDetails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLImages", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("EmailId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmailId1")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IncludeBol")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IncludeShippingLabels")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ShippingLabelsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShippingLabelsId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmailId1");

                    b.HasIndex("ShippingLabelsId1");

                    b.ToTable("BOLImages");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLImagesEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string[]>("Addresses")
                        .HasColumnType("text[]");

                    b.Property<Guid>("BOLImagesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool?>("IncludeBol")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IncludeLabels")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLImagesEmails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLImagesShippingLables", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BOLImagesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Position")
                        .HasColumnType("integer");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLImagesShippingLables");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLNotifications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BOLId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BOLId");

                    b.ToTable("BOLNotifications");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Terms")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLPayments");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLReferenceNumbers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<List<string>>("Bol")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MasterBol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuoteId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShipmentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("BOLReferenceNumbers");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLReferenceNumbersAdditionalReferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("BOLReferenceNumbersId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BOLReferenceNumbersId");

                    b.ToTable("BOLReferenceNumbersAdditionalReferences");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLReferenceNumbersPO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AdditionalShipperInfo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BOLReferenceNumbersId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("Palletized")
                        .HasColumnType("boolean");

                    b.Property<int?>("Pieces")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Weight")
                        .HasColumnType("integer");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BOLReferenceNumbersId");

                    b.ToTable("BOLReferenceNumbersPOs");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLShipmentTotals", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("Cube")
                        .HasColumnType("integer");

                    b.Property<string>("CubeDimensionsUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DeclaredValue")
                        .HasColumnType("integer");

                    b.Property<string>("DimensionsUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("GrossWeight")
                        .HasColumnType("integer");

                    b.Property<int?>("HandlingUnits")
                        .HasColumnType("integer");

                    b.Property<int?>("LinearLength")
                        .HasColumnType("integer");

                    b.Property<int?>("NetWeight")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("WeightUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BOLShipmentTotals");
                });

            modelBuilder.Entity("dotnet_example.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("Alert")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("DeltaPressure")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IdealPressure")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LimitTemperature")
                        .HasColumnType("numeric");

                    b.Property<string>("MeasureUnits")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("dotnet_example.Models.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("Address1")
                        .HasColumnType("text");

                    b.Property<string>("Address2")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CustomsBrokerType")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("LicenseNo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("dotnet_example.Models.BOL", b =>
                {
                    b.HasOne("dotnet_example.Models.BOLAccessorials", "Accessorials")
                        .WithMany()
                        .HasForeignKey("AccessorialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLCommodities", "Commodities")
                        .WithMany()
                        .HasForeignKey("BOLCommoditiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLImages", "Images")
                        .WithMany()
                        .HasForeignKey("BOLImagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLPayment", "Payment")
                        .WithMany()
                        .HasForeignKey("BOLPaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLReferenceNumbers", "ReferenceNumbers")
                        .WithMany()
                        .HasForeignKey("BOLReferenceNumbersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLShipmentTotals", "ShipmentTotals")
                        .WithMany()
                        .HasForeignKey("BOLShipmentTotalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.Contact", "BillTo")
                        .WithMany()
                        .HasForeignKey("BillToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.Contact", "CustomsBroker")
                        .WithMany()
                        .HasForeignKey("CustomsBrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.Contact", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.Contact", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accessorials");

                    b.Navigation("BillTo");

                    b.Navigation("Commodities");

                    b.Navigation("CustomsBroker");

                    b.Navigation("Destination");

                    b.Navigation("Images");

                    b.Navigation("Origin");

                    b.Navigation("Payment");

                    b.Navigation("ReferenceNumbers");

                    b.Navigation("ShipmentTotals");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorials", b =>
                {
                    b.HasOne("dotnet_example.Models.BOLAccessorialsAppointmentDetails", "AppointmentDetails")
                        .WithMany()
                        .HasForeignKey("AppointmentDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLAccessorialsCod", "Cod")
                        .WithMany()
                        .HasForeignKey("CodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLAccessorialsFullValueCoverageDetails", "FullValueCoverageDetails")
                        .WithMany()
                        .HasForeignKey("FullValueCoverageDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLAccessorialsHazardousDetails", "HazardousDetails")
                        .WithMany()
                        .HasForeignKey("HazardousDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLAccessorialsLimitedAccessType", "LimitedAccessType")
                        .WithMany()
                        .HasForeignKey("LimitedAccessTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLAccessorialsMarkDetails", "MarkDetails")
                        .WithMany()
                        .HasForeignKey("MarkDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLAccessorialsSortAndSegregateDetails", "SortAndSegregateDetails")
                        .WithMany()
                        .HasForeignKey("SortAndSegregateDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLAccessorialsTimeCriticalDetails", "TimeCriticalDetails")
                        .WithMany()
                        .HasForeignKey("TimeCriticalDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppointmentDetails");

                    b.Navigation("Cod");

                    b.Navigation("FullValueCoverageDetails");

                    b.Navigation("HazardousDetails");

                    b.Navigation("LimitedAccessType");

                    b.Navigation("MarkDetails");

                    b.Navigation("SortAndSegregateDetails");

                    b.Navigation("TimeCriticalDetails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsCod", b =>
                {
                    b.HasOne("dotnet_example.Models.Contact", "RemitTo")
                        .WithMany()
                        .HasForeignKey("RemitToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RemitTo");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsHazardousDetailsEmergencyContact", b =>
                {
                    b.HasOne("dotnet_example.Models.BOLAccessorialsHazardousDetails", null)
                        .WithOne("EmergencyContact")
                        .HasForeignKey("dotnet_example.Models.BOLAccessorialsHazardousDetailsEmergencyContact", "BOLAccessorialsHazardousDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_example.Models.BOLCommmoditiesLineItems", b =>
                {
                    b.HasOne("dotnet_example.Models.BOLCommoditiesHandlingUnits", null)
                        .WithMany("LineItems")
                        .HasForeignKey("BOLCommoditiesHandlingUnitsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLCommoditiesHazardousDetails", "HazardousDetails")
                        .WithMany()
                        .HasForeignKey("BOLCommoditiesHazardousDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HazardousDetails");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLCommoditiesHandlingUnits", b =>
                {
                    b.HasOne("dotnet_example.Models.BOLCommodities", null)
                        .WithMany("HandlingUnits")
                        .HasForeignKey("BOLCommoditiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_example.Models.BOLImages", b =>
                {
                    b.HasOne("dotnet_example.Models.BOLImagesEmail", "Email")
                        .WithMany()
                        .HasForeignKey("EmailId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("dotnet_example.Models.BOLImagesShippingLables", "ShippingLabels")
                        .WithMany()
                        .HasForeignKey("ShippingLabelsId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Email");

                    b.Navigation("ShippingLabels");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLNotifications", b =>
                {
                    b.HasOne("dotnet_example.Models.BOL", null)
                        .WithMany("Notifications")
                        .HasForeignKey("BOLId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_example.Models.BOLReferenceNumbersAdditionalReferences", b =>
                {
                    b.HasOne("dotnet_example.Models.BOLReferenceNumbers", null)
                        .WithMany("AdditionalReferences")
                        .HasForeignKey("BOLReferenceNumbersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_example.Models.BOLReferenceNumbersPO", b =>
                {
                    b.HasOne("dotnet_example.Models.BOLReferenceNumbers", null)
                        .WithMany("Po")
                        .HasForeignKey("BOLReferenceNumbersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_example.Models.Contact", b =>
                {
                    b.HasOne("dotnet_example.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("dotnet_example.Models.BOL", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLAccessorialsHazardousDetails", b =>
                {
                    b.Navigation("EmergencyContact")
                        .IsRequired();
                });

            modelBuilder.Entity("dotnet_example.Models.BOLCommodities", b =>
                {
                    b.Navigation("HandlingUnits");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLCommoditiesHandlingUnits", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("dotnet_example.Models.BOLReferenceNumbers", b =>
                {
                    b.Navigation("AdditionalReferences");

                    b.Navigation("Po");
                });
#pragma warning restore 612, 618
        }
    }
}
