/* 
 * Electronic Bill Of Lading Service
 *
 * This document provides an electronic Bill of Lading (eBOL). The eBOL is a legal document that provides a contract between the shipper, carrier and consignee stating what goods are being shipped, where the shipment is coming from and where it’s headed to. “Pro” number is the unique identifier for the document for update and delete functions.
 *
 * OpenAPI spec version: 2.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace dotnet_example.RequestModels.BOL.v202
{
    /// <summary>
    /// BOLRequestAccessorialsAppointmentDetails
    /// </summary>
    [DataContract]
        public partial class BOLRequestAccessorialsAppointmentDetails :  IEquatable<BOLRequestAccessorialsAppointmentDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BOLRequestAccessorialsAppointmentDetails" /> class.
        /// </summary>
        /// <param name="pickup">pickup.</param>
        /// <param name="delivery">delivery.</param>
        public BOLRequestAccessorialsAppointmentDetails(BOLRequestAccessorialsAppointmentDetailsPickup pickup = default(BOLRequestAccessorialsAppointmentDetailsPickup), BOLRequestAccessorialsAppointmentDetailsDelivery delivery = default(BOLRequestAccessorialsAppointmentDetailsDelivery))
        {
            this.Pickup = pickup;
            this.Delivery = delivery;
        }
        
        /// <summary>
        /// Gets or Sets Pickup
        /// </summary>
        [DataMember(Name="pickup", EmitDefaultValue=false)]
        public BOLRequestAccessorialsAppointmentDetailsPickup Pickup { get; set; }

        /// <summary>
        /// Gets or Sets Delivery
        /// </summary>
        [DataMember(Name="delivery", EmitDefaultValue=false)]
        public BOLRequestAccessorialsAppointmentDetailsDelivery Delivery { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BOLRequestAccessorialsAppointmentDetails {\n");
            sb.Append("  Pickup: ").Append(Pickup).Append("\n");
            sb.Append("  Delivery: ").Append(Delivery).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BOLRequestAccessorialsAppointmentDetails);
        }

        /// <summary>
        /// Returns true if BOLRequestAccessorialsAppointmentDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of BOLRequestAccessorialsAppointmentDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BOLRequestAccessorialsAppointmentDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Pickup == input.Pickup ||
                    (this.Pickup != null &&
                    this.Pickup.Equals(input.Pickup))
                ) && 
                (
                    this.Delivery == input.Delivery ||
                    (this.Delivery != null &&
                    this.Delivery.Equals(input.Delivery))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pickup != null)
                    hashCode = hashCode * 59 + this.Pickup.GetHashCode();
                if (this.Delivery != null)
                    hashCode = hashCode * 59 + this.Delivery.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
