/* 
 * Electronic Bill Of Lading Service
 *
 * This document provides an electronic Bill of Lading (eBOL). The eBOL is a legal document that provides a contract between the shipper, carrier and consignee stating what goods are being shipped, where the shipment is coming from and where it’s headed to. “Pro” number is the unique identifier for the document for update and delete functions.
 *
 * OpenAPI spec version: 2.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace dotnet_example.RequestModels.BOL.v202
{
    /// <summary>
    /// BOLRequestImagesEmail
    /// </summary>
    [DataContract]
        public partial class BOLRequestImagesEmail :  IEquatable<BOLRequestImagesEmail>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BOLRequestImagesEmail" /> class.
        /// </summary>
        /// <param name="includeBol">Used to request the bill of lading PDF to be sent to one or more email addresses .</param>
        /// <param name="includeLabels">Used to request the shipping labels PDF to be sent to one or more email addresses .</param>
        /// <param name="addresses">Provide one or more email addresses to receive the bol and/or shipping labels PDF .</param>
        public BOLRequestImagesEmail(bool? includeBol = default(bool?), bool? includeLabels = default(bool?), List<string> addresses = default(List<string>))
        {
            this.IncludeBol = includeBol;
            this.IncludeLabels = includeLabels;
            this.Addresses = addresses;
        }
        
        /// <summary>
        /// Used to request the bill of lading PDF to be sent to one or more email addresses 
        /// </summary>
        /// <value>Used to request the bill of lading PDF to be sent to one or more email addresses </value>
        [DataMember(Name="includeBol", EmitDefaultValue=false)]
        public bool? IncludeBol { get; set; }

        /// <summary>
        /// Used to request the shipping labels PDF to be sent to one or more email addresses 
        /// </summary>
        /// <value>Used to request the shipping labels PDF to be sent to one or more email addresses </value>
        [DataMember(Name="includeLabels", EmitDefaultValue=false)]
        public bool? IncludeLabels { get; set; }

        /// <summary>
        /// Provide one or more email addresses to receive the bol and/or shipping labels PDF 
        /// </summary>
        /// <value>Provide one or more email addresses to receive the bol and/or shipping labels PDF </value>
        [DataMember(Name="addresses", EmitDefaultValue=false)]
        public List<string> Addresses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BOLRequestImagesEmail {\n");
            sb.Append("  IncludeBol: ").Append(IncludeBol).Append("\n");
            sb.Append("  IncludeLabels: ").Append(IncludeLabels).Append("\n");
            sb.Append("  Addresses: ").Append(Addresses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BOLRequestImagesEmail);
        }

        /// <summary>
        /// Returns true if BOLRequestImagesEmail instances are equal
        /// </summary>
        /// <param name="input">Instance of BOLRequestImagesEmail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BOLRequestImagesEmail input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.IncludeBol == input.IncludeBol ||
                    (this.IncludeBol != null &&
                    this.IncludeBol.Equals(input.IncludeBol))
                ) && 
                (
                    this.IncludeLabels == input.IncludeLabels ||
                    (this.IncludeLabels != null &&
                    this.IncludeLabels.Equals(input.IncludeLabels))
                ) && 
                (
                    this.Addresses == input.Addresses ||
                    this.Addresses != null &&
                    input.Addresses != null &&
                    this.Addresses.SequenceEqual(input.Addresses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.IncludeBol != null)
                    hashCode = hashCode * 59 + this.IncludeBol.GetHashCode();
                if (this.IncludeLabels != null)
                    hashCode = hashCode * 59 + this.IncludeLabels.GetHashCode();
                if (this.Addresses != null)
                    hashCode = hashCode * 59 + this.Addresses.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
