/* 
 * Electronic Bill Of Lading Service
 *
 * This document provides an electronic Bill of Lading (eBOL). The eBOL is a legal document that provides a contract between the shipper, carrier and consignee stating what goods are being shipped, where the shipment is coming from and where it’s headed to. “Pro” number is the unique identifier for the document for update and delete functions.
 *
 * OpenAPI spec version: 2.0.2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
namespace dotnet_example.RequestModels.BOL.v202
{
    /// <summary>
    /// BOLRequestAccessorialsTimeCriticalDetails
    /// </summary>
    [DataContract]
        public partial class BOLRequestAccessorialsTimeCriticalDetails :  IEquatable<BOLRequestAccessorialsTimeCriticalDetails>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BOLRequestAccessorialsTimeCriticalDetails" /> class.
        /// </summary>
        /// <param name="type">Type of delivery required for the requested Time Critical Service.  Required when accessorials.code list include TCS.  Valid Values: See the Time_Critical_Types schema at the bottom of this page. .</param>
        /// <param name="date">date.</param>
        public BOLRequestAccessorialsTimeCriticalDetails(string type = default(string), BOLRequestAccessorialsTimeCriticalDetailsDate date = default(BOLRequestAccessorialsTimeCriticalDetailsDate))
        {
            this.Type = type;
            this.Date = date;
        }
        
        /// <summary>
        /// Type of delivery required for the requested Time Critical Service.  Required when accessorials.code list include TCS.  Valid Values: See the Time_Critical_Types schema at the bottom of this page. 
        /// </summary>
        /// <value>Type of delivery required for the requested Time Critical Service.  Required when accessorials.code list include TCS.  Valid Values: See the Time_Critical_Types schema at the bottom of this page. </value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public BOLRequestAccessorialsTimeCriticalDetailsDate Date { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BOLRequestAccessorialsTimeCriticalDetails {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BOLRequestAccessorialsTimeCriticalDetails);
        }

        /// <summary>
        /// Returns true if BOLRequestAccessorialsTimeCriticalDetails instances are equal
        /// </summary>
        /// <param name="input">Instance of BOLRequestAccessorialsTimeCriticalDetails to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BOLRequestAccessorialsTimeCriticalDetails input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
